version: '3'

services:
  postgres:
    image: 'postgres:13-alpine'
    container_name: postgresdb-gobarber
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: "gobarber"
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DB: "gobarberdb"
    volumes:
      - $HOME/dataset/gobarber/postgres:/var/lib/postgresql/data

  mongo:
    image: 'mongo'
    container_name: mongo-gobarber
    ports:
      - '27017:27017'
    volumes:
      -  $HOME/dataset/gobarber/mongo:/data/db

  regis:
    image: 'redis:alpine'
    container_name: redis-gobarber
    ports:
      - '6379:6379'
    volumes:
      -  $HOME/dataset/gobarber/redis:/usr/local/etc/redi
